services:
  nyc-taxi-warehouse:
    build: .
    environment:
      TAXI_DATA_URL: ${TAXI_DATA_URL}
      TAXI_ZONE_LOOKUP_URL: ${TAXI_ZONE_LOOKUP_URL}
      TAXI_DATA_FILENAME: ${TAXI_DATA_FILENAME}
      TAXI_ZONE_LOOKUP_TABLE: ${TAXI_ZONE_LOOKUP_TABLE}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports